name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Updated to a version with Dart >=3.3.0

      - name: Install dependencies
        run: |
          cd lpmt
          flutter pub get

      - name: Build APK
        run: |
          cd lpmt
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: lpmt/build/app/outputs/flutter-apk/app-release.apk

